language: php
php:
  - 5.6

before_install:
  - composer self-update

before_script:
  - composer install
  - composer diagnose

script: phpunit --configuration phpunit.xml --coverage-text

#
#language: php
#php:
# - '5.6.30'
#before_script:
# -curl -s http://getcomposer.org/installer | php
# - php composer.phar install
# sript: phpunit
