language: php
php:
  - '5.6.30'
before_install:
  - php /home/travis/.phpenv/versions/5.6.3/bin/composer.phar self-update
  before_script:
    - composer install
script: phpunit --configuration phpunit.xml --coverage-text

#language: php
#php:
# - '5.6.30'
#before_script:
# -curl -s http://getcomposer.org/installer | php
# - php composer.phar install
# sript: phpunit
